### ISSUE TITLE
Path does not chain with any of the trust anchors

### ISSUE THREAD

**Issue by OPhamster** [khezen/docker-elasticsearch#11]
I made 3 separate master/client/data nodes - each of them using the Dockerfile. 
The client node has the following config: 
```
Name:                   es-client
Namespace:              default
CreationTimestamp:      Sat, 06 May 2017 13:10:27 +0530
Labels:                 component=elasticsearch
                        role=client
Annotations:            deployment.kubernetes.io/revision=1
                        kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"component":"elasticsearch","role":"client"},"name":"es-c...
Selector:               component=elasticsearch,role=client
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:       component=elasticsearch
                role=client
  Init Containers:
   sysctl:
    Image:      busybox
    Port:
    Command:
      sysctl
      -w
      vm.max_map_count=262144
    Environment:        <none>
    Mounts:             <none>
  Containers:
   es-client:
    Image:      es-sg:latest
    Ports:      9200/TCP, 9300/TCP
    Environment:
      NAMESPACE:         (v1:metadata.namespace)
      NODE_NAME:         (v1:metadata.name)
      CLUSTER_NAME:     elasticsearch
      NODE_MASTER:      false
      NODE_DATA:        false
      HTTP_ENABLE:      true
      ES_JAVA_OPTS:     -Xms256m -Xmx256m
    Mounts:
      /data from storage (rw)
  Volumes:
   storage:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
Conditions:
  Type          Status  Reason
  ----          ------  ------
  Available     True    MinimumReplicasAvailable
OldReplicaSets: <none>
NewReplicaSet:  <none>
Events:         <none>

`````
and the log for this client:

> Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:352) ~[?:?]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:260) ~[?:?]
	at sun.security.validator.Validator.validate(Validator.java:260) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136) ~[?:?]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1501) ~[?:?]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:?]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026) ~[?:?]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:966) ~[?:?]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:963) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1416) ~[?:?]
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1167) ~[?:?]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1080) ~[?:?]
	... 17 more

I havent changed much in the Dockerfile except for setting a few environment variables - so I'm not sure how the certificate path is causing problems.

**Comment by Khezen** [comment]
I am very busy right now and I don't have much time to maintain the image. I'll have a look on saturday. On the other hand, contribution would be much appreciated.

**Comment by khezen** [comment]
@OPhamster can I see the Dockerfile?

**Comment by OPhamster** [comment]
Yeah sorry about the delay - Fixed it. Essentially the configurations were set as if a single node was Master, Client and Data - I had to make changes to entrypoint.sh and elasticsearch.yml I also had to establish a PKI like structure as said in the documentation.

sgadmin.sh:
![entrypoint](https://cloud.githubusercontent.com/assets/12889745/26390426/2280e9aa-407c-11e7-925c-3185ecb62f55.png)
elasticsearch.yml:
![elasticsearch_yml](https://cloud.githubusercontent.com/assets/12889745/26390511/77e70fdc-407c-11e7-995e-22990f5604ac.png)

**Comment by Khezen** [comment]
Great! It would be great if you could submit a pull request for this. Otherwise I'll integrate your changes when I'll have time.
