### ISSUE TITLE
Version 6.X stuck Stalling for Elasticsearch...

### ISSUE THREAD

**Issue by exit99** [khezen/docker-elasticsearch#37]
Using the example docker-compose file in the readme.  Works well with version 5, but stalls on version 6

```
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch_1  |      ... 6 more
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
elasticsearch_1  | Stalling for Elasticsearch...
```

**Comment by pgbezerra** [comment]
Could you send a more complete log?

**Comment by exit99** [comment]
I've moved to just overriding the official docker-image. 

I probably was holding it wrong. 

Closing the issue.

Thanks.

**Comment by kleptog** [comment]
Hoi, just want to say we've been getting this for a while now. The error is basically that it cannot access the specified temporary directory /es_tmp. You can fix it by going into the container and chowning it.

Overriding ES_TMPDIR=/tmp in the docker-compose file also fixes it.

```
Stalling for Elasticsearch...
JNA Warning: IOException removing temporary files: JNA temporary directory '/es_tmp' does not exist
[2018-05-03T11:45:52,217][WARN ][o.e.b.Natives            ] unable to load JNA native support library, native methods will be disabled.
java.lang.UnsatisfiedLinkError: Failed to create temporary file for /com/sun/jna/linux-x86-64/libjnidispatch.so library: JNA temporary directory '/es_tmp' does not exist
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:962) ~[jna-4.5.1.jar:4.5.1 (b0)]
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922) ~[jna-4.5.1.jar:4.5.1 (b0)]
	at com.sun.jna.Native.<clinit>(Native.java:190) ~[jna-4.5.1.jar:4.5.1 (b0)]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_151]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_151]
	at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45) [elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:104) [elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:172) [elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) [elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.2.2.jar:6.2.2]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) [elasticsearch-6.2.2.jar:6.2.2]
[2018-05-03T11:45:52,230][WARN ][o.e.b.Natives            ] cannot check if running as root because JNA is not available
[2018-05-03T11:45:52,230][WARN ][o.e.b.Natives            ] cannot install system call filter because JNA is not available
[2018-05-03T11:45:52,231][WARN ][o.e.b.Natives            ] cannot register console handler because JNA is not available
[2018-05-03T11:45:52,233][WARN ][o.e.b.Natives            ] cannot getrlimit RLIMIT_NPROC because JNA is not available
[2018-05-03T11:45:52,234][WARN ][o.e.b.Natives            ] cannot getrlimit RLIMIT_AS beacuse JNA is not available
[2018-05-03T11:45:52,234][WARN ][o.e.b.Natives            ] cannot getrlimit RLIMIT_FSIZE because JNA is not available
[2018-05-03T11:45:52,339][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [NODE-1] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unable to access 'java.io.tmpdir' (/es_tmp)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.2.2.jar:6.2.2]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.2.2.jar:6.2.2]
Caused by: java.lang.IllegalStateException: Unable to access 'java.io.tmpdir' (/es_tmp)
	at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:70) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:299) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:262) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Security.configure(Security.java:123) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:208) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.2.jar:6.2.2]
	... 6 more
Caused by: java.nio.file.AccessDeniedException: /es_tmp
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:1.8.0_151]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_151]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_151]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:1.8.0_151]
	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_151]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_151]
	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_151]
	at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:421) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:68) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:299) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:262) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Security.configure(Security.java:123) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:208) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.2.jar:6.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.2.jar:6.2.2]
	... 6 more
Stalling for Elasticsearch...
Stalling for Elasticsearch...
Stalling for Elasticsearch...
Stalling for Elasticsearch...
Stalling for Elasticsearch...
```

**Comment by khezen** [comment]
not reproduced on latest build
