### ISSUE TITLE
Volumes: Exception in thread "main" java.nio.file.NoSuchFileException: /elasticsearch/config/jvm.options

### ISSUE THREAD

**Issue by xermus** [khezen/docker-elasticsearch#45]
I am running Docker on an Ubuntu 18 server.

```
docker run -d --name elasticsearch --security-opt apparmor=unconfined -v /data/elasticsearch-data:/elasticsearch/data -v /data/elasticsearch-config:/elasticsearch/config -p 9200:9200 -p 9300:9300 -e ELASTIC_PWD=changeme -e KIBANA_PWD=changeme khezen/elasticsearch:latest
```

Before running the above command I created 

- /data/elasticsearch-data
- /data/elasticsearch-config

on the host machine having user:docker rights (where the docker group has write rights also). However, I am getting this error:

Stalling for Elasticsearch...
Exception in thread "main" java.nio.file.NoSuchFileException: /elasticsearch/config/jvm.options
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:60)
Stalling for Elasticsearch...

Not sure where the problem is. The setup looks OK to me. I also did a "chown 1000:1000" in the container" for the shared folders without any success. Does anyone have an idea?

**Comment by xermus** [comment]
The volume for the data container worked out of the box. I just changed the path for the config like this pointing directly to the elasticsearch.yml file:

```
docker run -d --name elasticsearch --security-opt apparmor=unconfined -v /data/elasticsearch-data:/elasticsearch/data -v /data/elasticsearch-config/elasticsearch.yml:/elasticsearch/config/elasticsearch.yml -p 9200:9200 -p 9300:9300 -e ELASTIC_PWD=changeme -e KIBANA_PWD=changeme khezen/elasticsearch:latest
```

.. and this way it seems to work. Is this path to elasticsearch.yml correct?


Also: When I want to set an inital IP address like so

-e NETWORK_HOST=172.17.0.101

the IP is not taken when I stop/remove the container and bring it up with a parameter like this ^^. How do you assign static IPs if you have several containers which need to talk to each other?

**Comment by khezen** [comment]
Please check this thread. https://github.com/khezen/docker-elasticsearch/issues/45

for more material about how volumes work https://docs.docker.com/storage/volumes/
for more material about networking https://docs.docker.com/network/
