### ISSUE TITLE
Misconfiguration loopback

### ISSUE THREAD

**Issue by bclermont** [khezen/docker-elasticsearch#7]
Unchanged configuration file, at startup:

```
elasticsearch             | [2017-04-03T00:48:47,536][WARN ][o.e.d.z.UnicastZenPing   ] [ezwfxYV] failed to resolve host [['127.0.0.1']
elasticsearch             | java.lang.IllegalArgumentException: Invalid bracketed host/port range: ['127.0.0.1'
elasticsearch             | 	at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:831) ~[elasticsearch-5.3.0.jar:5.3.0]
elasticsearch             | 	at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:812) ~[elasticsearch-5.3.0.jar:5.3.0]
elasticsearch             | 	at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:665) ~[elasticsearch-5.3.0.jar:5.3.0]
elasticsearch             | 	at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$null$0(UnicastZenPing.java:212) ~[elasticsearch-5.3.0.jar:5.3.0]
elasticsearch             | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
elasticsearch             | 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:544) [elasticsearch-5.3.0.jar:5.3.0]
elasticsearch             | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
elasticsearch             | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
elasticsearch             | 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
elasticsearch             | [2017-04-03T00:48:47,570][WARN ][o.e.d.z.UnicastZenPing   ] [ezwfxYV] failed to resolve host ['[::1]']]
elasticsearch             | java.lang.IllegalArgumentException: IPv6 addresses must be bracketed: '[::1]']
elasticsearch             | 	at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:846) ~[elasticsearch-5.3.0.jar:5.3.0]
elasticsearch             | 	at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:812) ~[elasticsearch-5.3.0.jar:5.3.0]
elasticsearch             | 	at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:665) ~[elasticsearch-5.3.0.jar:5.3.0]
elasticsearch             | 	at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$null$0(UnicastZenPing.java:212) ~[elasticsearch-5.3.0.jar:5.3.0]
elasticsearch             | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
elasticsearch             | 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:544) [elasticsearch-5.3.0.jar:5.3.0]
elasticsearch             | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
elasticsearch             | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
elasticsearch             | 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by khezen** [comment]
Yes I spotted that while moving to 5.3. I'll fix it soon. Thank you.

**Comment by khezen** [comment]
It should be better now

**Comment by bclermont** [comment]
```
elasticsearch             | [2017-04-03T02:15:06,402][WARN ][o.e.d.z.UnicastZenPing   ] [6c1885a55e32] failed to resolve host [::1]
elasticsearch             | java.lang.IllegalArgumentException: IPv6 addresses must be bracketed: ::1
elasticsearch             | 	at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:846) ~[elasticsearch-5.3.0.jar:5.3.0]
elasticsearch             | 	at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:812) ~[elasticsearch-5.3.0.jar:5.3.0]
elasticsearch             | 	at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:665) ~[elasticsearch-5.3.0.jar:5.3.0]
elasticsearch             | 	at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$null$0(UnicastZenPing.java:212) ~[elasticsearch-5.3.0.jar:5.3.0]
elasticsearch             | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
elasticsearch             | 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:544) [elasticsearch-5.3.0.jar:5.3.0]
elasticsearch             | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
elasticsearch             | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
elasticsearch             | 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
elasticsearch             | Stalling for Elasticsearch...
```

**Comment by khezen** [comment]
fixed
